import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";

const font = Space_Grotesk({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: "NextERD",
  description: "Generated by vaxad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
